### ISSUE TITLE
pnpm scripts

### ISSUE THREAD

**Issue by ss-o** [z-shell/zw#186]
Hey @devinrhode2,

Any ideas why pnpm fails to run scripts? As a workaround, I use `exec` as the example below.

https://github.com/z-shell/zw/blob/975820865a6c7a4658f25faca9916f140a96f947/.github/README.md?plain=1#L102

However, it should be: `pnpm start --locale ja`

**Comment by devinrhode2** [comment]
How exactly would I reproduce this issue?
Checkout that repo at that sha... then what?

**Comment by ss-o** [comment]
`pnpm i`
`pnpm start --locale ja`
