### ISSUE TITLE
bug: zi ignore zi_home

### ISSUE THREAD

**Issue by onokatio** [z-shell/zw#385]
### Environment

OSTYPE=darwin21.3.0 CPUTYPE=arm64 / MACHINE_TYPE=arm ZSH_VERSION=5.8.1

### Expected behavior

following document (https://z.digitalclouds.dev/ja/docs/getting_started/installation), `$zi_home` will be used as a install path for zi.

### Current behavior

`$zi_home` is ignored.

### Steps to reproduce

```
export zi_home="~/cache/zi"
```

### Code snippet

```
export zi_home="~/cache/zi"
git clone https://github.com/z-shell/zi.git "$zi_home/bin"
source "${zi_home}/bin/zi.zsh"
autoload -Uz _zi
(( ${+_comps} )) && _comps[zi]=_zi
```

### Aditional information

I think document is mistake and `ZI[HOME_DIR]` is correct.

https://github.com/z-shell/zi/blob/main/zi.zsh#L46

**Comment by ss-o** [comment]
@onokatio is it better now or more detailed instructions would be better?
https://z.digitalclouds.dev/ja/docs/getting_started/installation :octocat:
