### ISSUE TITLE
docs: fix broken links in Community > Gallery ... > Completions

### ISSUE THREAD

**Issue by 0xMRTT** [z-shell/zw#679]
### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/z-shell/zi/blob/main/docs/CONTRIBUTING.md).

### Description

There is a something like 3 or 4 broken links inside this page.

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by ss-o** [comment]
Branch to merge: 

```shell
git fetch
git checkout 679-docs-fix-broken-links-in-community-gallery-completions
```
